<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PS2000_GUI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PS2000.Driver\PS2000.Driver.csproj" />
  </ItemGroup>

</Project>
